### ISSUE TITLE
Edit->"Common" tab does not update unless switched to from Tone tab

### ISSUE THREAD

**Issue by DaforLynx** [giulioz/jv880_juce#6]
Title. You also cannot actually edit patches but that is probably an intentionally missing feature for now.

**Comment by TheRaven73** [comment]
Yeah, this feature would be great. At least turning tones on/off, panning and effect routing.

**Comment by mkruselj** [comment]
Should be fixed now after Python Blue's additions.

**Comment by DaforLynx** [comment]
@mkruselj er, no. at least not in the current commit on main. still need to reload it from the Tone tab.

<img width="815" height="735" alt="Image" src="https://github.com/user-attachments/assets/138e3b2e-78e2-42b0-8107-62d62fe5c025" />

**Comment by DaforLynx** [comment]
Can confirm even that does not fix this specific issue. Please reopen it.
