### ISSUE TITLE
Audible crackling noise when running the plugin at buffer size of 128 samples

### ISSUE THREAD

**Issue by mkruselj** [giulioz/jv880_juce#9]
Yep. As soon as I set the ASIO buffer to 256 samples, everything sounds clean again.

**Comment by DaforLynx** [comment]
That's likely due to CPU load. This is a fairly intensive plugin, and it might just be too much to process in just 128 samples per buffer.

**Comment by mkruselj** [comment]
Nope, it's not that, CPU is around 5% over here when making it play full polyphony, no core is getting saturated in the least, this is with an i7-6700K@4.3 GHz, so a bit older CPU but it can still run heavy-hitter plugins. This is not a heavy-hitter plugin compared to Diva, Repro-5, Pigments, Serum...

**Comment by mkruselj** [comment]
Another data point: this only seems to happen in standalone over here, doesn't happen when I load the VST3 in Reaper.

**Comment by DaforLynx** [comment]
Ok, I'm testing on Linux and I can confirm that, for some reason, crackling appears in the standalone build for exactly the 128 sample buffer setting. But interestingly, if I go *lower* it is not present/barely noticeable.

**Comment by mkruselj** [comment]
Oh! I haven't tested 64 samples over here. That's very interesting, if true. I'll test over here, then report back.

**Comment by giulioz** [comment]
I think it's very likely a problem with the sample rate conversion, I'll investigate

**Comment by TheRaven73** [comment]
I can confirm this behaviour under macOS, AU plugin, DAW Reaper. Sound is clean again when switching either to 64 or 256 samples.
To be precise, it sonded mor like an aliasing distortion to me, depending much in the sound chosen. In certain regimes of the keyboard it really sounds more like "crackling".

Amazing plugin, keep up the good work!

**Comment by Benis67** [comment]
> I think it's very likely a problem with the sample rate conversion, I'll investigate

I have the same problem with my RME BabyFace Pro with sample rate at 48KHz (Windows 11). No problem with 44.1 Hkz even with small buffers (96 samples).
Another problem is the distortions in certain sounds when using high dynamics or polyphony (see eg Jazz Organ1- whistle...) in JV880 Factory.

**Comment by mkruselj** [comment]
Some sounds can definitely clip the output, turn down the track volume in host to counteract.

**Comment by bczow** [comment]
@giulioz If you are gathering information, I can attest the following:

1. No crackles related to ASIO buffer here (Reaper, Win10, ASIO @128 samples, 44,1 kHz, on a quite old laptop).

2. Internal clipping is rare, but occurs e.g. if I hit a chord with max velocity playing the Analog Horn patch. (Lowering the track volume in the DAW does not help in this case.)

**Comment by Sylian1** [comment]
I've got internal clipping too when I play layering sounds like chords.
I try to change project frequency 48Khz down to 44Khz but same issue.
Lowering the track volume doesn't wok. It's come from the VST3

**Comment by synthdude** [comment]
I was able to defeat the crackeling audio (saturated output), by using a cheap Edirol USB controller that have some sliders on it, and one of the sliders was controlling the overall patch volume, so now all is good again.

**Comment by mkruselj** [comment]
I suppose if you send it MIDI CC7 from piano roll it will help...

**Comment by bczow** [comment]
If I lower the volume of e.g. the Pizza Hut patch using MIDI CC 07 (to the value, say 95) and save the DAW project, will the plugin remember that on reopening? I'm asking because I cannot test it myself at the moment.

**Comment by mkruselj** [comment]
Your host is supposed to chase the correct MIDI CC values on playback.

**Comment by bczow** [comment]
@mkruselj If they are recorded. But if I send MIDI CC from a keyboard, without recording on track, the plugin will still follow it (I supose). But will it store the state for the next time I open the session? (If I save the session after it received CC, of course.)

**Comment by mkruselj** [comment]
> I just released a new version which should fix a lot of crackling noise issues: in the pcm chip emulation, the 20 bit addition code was broken, causing problems with the filter in some cases.

It's fixed now! You can close this issue, as far as I'm concerned. Thank you! :)

**Comment by bczow** [comment]
> > [@mkruselj](https://github.com/mkruselj) If they are recorded. But if I send MIDI CC from a keyboard, without recording on track, the plugin will still follow it (I supose). But will it store the state for the next time I open the session? (If I save the session after it received CC, of course.)
> 
> No, the plugin won't remember it. You should have it recorded on a track in your DAW project, that's the expected way these things should work.

I was thinking about such a workaround because of the crackles. But today's update solved the problem and made this method unnecessary.

**Comment by TheRaven73** [comment]
Unfortunately, the same here. I run REAPER under 48kHz/24bit/128 Samples, and still have the crackling issues. Maybe less pronounced as before, but still very unpleasant. 
Switchching the buffer to either 64 or 256 samples totally eradicates the issue, and the plugin sounds wonderful.
I's definitively not an overdrive / VU issue.

**Comment by Seljo1** [comment]
Tested in Reaper (Windows)

48.0 kHz 64 Samples = ok
48.0 kHz 96 Samples = ok
48.0 kHz 128 Samples = crackles
48.0 kHz 256 Samples = ok

44.1 kHz 64 Samples = crackles
44.1 kHz 96 Samples = ok
44.1 kHz 128 Samples = ok
44.1 kHz 256 Samples = ok

**Comment by temporal-distortion** [comment]
Issue seems to still be there unfortunately. Even if i run an older cpu (4790k) i don't really have these issues on any other plug. Tried to bump the buffer anywhere between 256-512 (8-12ms latency) and downloaded also the latest vst, and maybe its better now in a sense, but the static is there now and then still.

**Comment by jounih** [comment]
logic AU here - can confirm too, aliasing noise at 32ms and 64ms at 48khz, sounds fine at 128ms. sounds incredible otherwise. the reverb/chorus controls and tone tab don't work yet, right? Thank you for this wonderful plugin. jv1080 next?

**Comment by itsbacho** [comment]
if your using FL Studio go into turn on just mess with the used fix size buffers setting and the noise should be gone. worked for me 

<img width="565" height="483" alt="Image" src="https://github.com/user-attachments/assets/d2eaa7f3-359c-4590-a4b2-2590e921de8e" />

**Comment by bfunc** [comment]
> if your using FL Studio go into turn on just mess with the used fix size buffers setting and the noise should be gone. worked for me
Worked, thanks a lot!
